Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/grpc/_server.py", line 552, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "/nb/server.py", line 24, in RecordTemps
    station_id = request.station_id
AttributeError: station_id
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/grpc/_server.py", line 552, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "/nb/server.py", line 39, in StationMax
    station_id = request.station_id
AttributeError: station_id
